### PR TITLE
JSONHTMLBuilder location changed in newer Sphinx's

### PR DESCRIPTION
**Pull request by nugend**
Fixes a defect when running against Sphinx. Not sure which version

### CODE REVIEW

**Comment by spyoungtech** [comment]
Looks good to me. 

Thanks for the contribution @nugend

**Review by spyoungtech — COMMENTED** [review]
LGTM

**Comment by spyoungtech** [comment]
@ikeeip when possible, can we release this as a new version on PyPI?

I'd be happy to do so myself, if I had maintainer rights on PyPI 😁 

Thanks!

**Comment by ikeeip** [comment]
> @ikeeip when possible, can we release this as a new version on PyPI?
> 
> I'd be happy to do so myself, if I had maintainer rights on PyPI 😁
> 
> Thanks!

Sadly, but i have not access to PyPI too. I will try to contact with someone who can do it on the next week.

**Pull request merged**
